import assert from "node:assert/strict";
import test from "node:test";

import { chooseWithJev, JevUpstreamError } from "../jev-client.mjs";

const candidates = [
  { id: "f0_move_0", figure: 0, description: "Advance along a legal path." },
  { id: "f0_wait", figure: 0, description: "Wait in place." },
  { id: "f1_cover_2", figure: 1, description: "Take cover." },
  { id: "f1_wait", figure: 1, description: "Wait in place." },
];

function jsonResponse(body, status = 200, headers = {}) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json", ...headers },
  });
}

test("sends one typed Choice and returns its selected legal candidate", async () => {
  let calls = 0;
  const result = await chooseWithJev({
    apiKey: "test-only-key",
    state: { team: "blue", visible_enemies: [] },
    candidates,
    retries: 0,
    fetchImpl: async (_url, options) => {
      calls += 1;
      const payload = JSON.parse(options.body);
      assert.equal(payload.model, "jev-latest");
      assert.deepEqual(Object.keys(payload.questions), ["figure_0", "figure_1"]);
      assert.equal(payload.questions.figure_0.type, "choice");
      assert.deepEqual(Object.keys(payload.questions.figure_0.criteria), ["f0_move_0", "f0_wait"]);
      assert.deepEqual(Object.keys(payload.questions.figure_1.criteria), ["f1_cover_2", "f1_wait"]);
      assert.equal(options.headers.Authorization, "Bearer test-only-key");
      return jsonResponse({
        model: "jev-test",
        answers: {
          figure_0: { type: "choice", choice: "f0_move_0", confidence: 0.75 },
          figure_1: { type: "choice", choice: "f1_cover_2", confidence: 0.9 },
        },
      });
    },
  });
  assert.equal(calls, 1);
  assert.deepEqual(result, {
    choices: { 0: "f0_move_0", 1: "f1_cover_2" }, confidence: 0.75, model: "jev-test", attempts: 1,
  });
});

test("rejects an upstream choice that was not generated by game code", async () => {
  await assert.rejects(() => chooseWithJev({
    apiKey: "test-only-key",
    state: { team: "red" },
    candidates,
    retries: 0,
    fetchImpl: async () => jsonResponse({
      answers: {
        figure_0: { type: "choice", choice: "f1_wait", confidence: 1 },
        figure_1: { type: "choice", choice: "f1_wait", confidence: 1 },
      },
    }),
  }), JevUpstreamError);
});

test("bounds retry count on retryable upstream failures", async () => {
  let calls = 0;
  await assert.rejects(() => chooseWithJev({
    apiKey: "test-only-key",
    state: { team: "red" },
    candidates,
    retries: 1,
    fetchImpl: async () => {
      calls += 1;
      return jsonResponse({}, 503);
    },
  }), JevUpstreamError);
  assert.equal(calls, 2);
});

test("aborts a timed-out upstream request without unbounded retries", async () => {
  let calls = 0;
  await assert.rejects(() => chooseWithJev({
    apiKey: "test-only-key",
    state: { team: "red" },
    candidates,
    retries: 0,
    timeoutMs: 5,
    fetchImpl: async (_url, { signal }) => {
      calls += 1;
      return await new Promise((_resolve, reject) => {
        signal.addEventListener("abort", () => reject(new DOMException("aborted", "AbortError")));
      });
    },
  }), /timed out/);
  assert.equal(calls, 1);
});

test("does not spend an API call on a forced single legal choice", async () => {
  const result = await chooseWithJev({
    apiKey: "test-only-key",
    state: { team: "red" },
    candidates: [candidates[1], candidates[3]],
    fetchImpl: async () => { throw new Error("must not call upstream"); },
  });
  assert.deepEqual(result.choices, { 0: "f0_wait", 1: "f1_wait" });
  assert.equal(result.attempts, 0);

  // Only the figure with real options is put to the model.
  let asked;
  const mixed = await chooseWithJev({
    apiKey: "test-only-key",
    state: { team: "red" },
    candidates: [candidates[0], candidates[1], candidates[3]],
    fetchImpl: async (_url, options) => {
      asked = Object.keys(JSON.parse(options.body).questions);
      return jsonResponse({ answers: { figure_0: { type: "choice", choice: "f0_wait" } } });
    },
  });
  assert.deepEqual(asked, ["figure_0"]);
  assert.deepEqual(mixed.choices, { 0: "f0_wait", 1: "f1_wait" });
});
