import assert from "node:assert/strict";
import test from "node:test";

import { chooseWithJev, JevUpstreamError } from "../jev-client.mjs";

const candidates = [
  { id: "move_0", description: "Advance along a legal path." },
  { id: "wait", description: "Wait in place." },
];

function jsonResponse(body, status = 200, headers = {}) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json", ...headers },
  });
}

test("sends one typed Choice and returns its selected legal candidate", async () => {
  let calls = 0;
  const result = await chooseWithJev({
    apiKey: "test-only-key",
    state: { team: "blue", visible_enemies: [] },
    candidates,
    retries: 0,
    fetchImpl: async (_url, options) => {
      calls += 1;
      const payload = JSON.parse(options.body);
      assert.equal(payload.model, "jev-latest");
      assert.equal(payload.questions.action.type, "choice");
      assert.deepEqual(Object.keys(payload.questions.action.criteria), ["move_0", "wait"]);
      assert.equal(options.headers.Authorization, "Bearer test-only-key");
      return jsonResponse({
        model: "jev-test",
        answers: { action: { type: "choice", choice: "move_0", confidence: 0.75 } },
      });
    },
  });
  assert.equal(calls, 1);
  assert.deepEqual(result, { choice: "move_0", confidence: 0.75, model: "jev-test", attempts: 1 });
});

test("rejects an upstream choice that was not generated by game code", async () => {
  await assert.rejects(() => chooseWithJev({
    apiKey: "test-only-key",
    state: { team: "red" },
    candidates,
    retries: 0,
    fetchImpl: async () => jsonResponse({
      answers: { action: { type: "choice", choice: "teleport", confidence: 1 } },
    }),
  }), JevUpstreamError);
});

test("bounds retry count on retryable upstream failures", async () => {
  let calls = 0;
  await assert.rejects(() => chooseWithJev({
    apiKey: "test-only-key",
    state: { team: "red" },
    candidates,
    retries: 1,
    fetchImpl: async () => {
      calls += 1;
      return jsonResponse({}, 503);
    },
  }), JevUpstreamError);
  assert.equal(calls, 2);
});

test("aborts a timed-out upstream request without unbounded retries", async () => {
  let calls = 0;
  await assert.rejects(() => chooseWithJev({
    apiKey: "test-only-key",
    state: { team: "red" },
    candidates,
    retries: 0,
    timeoutMs: 5,
    fetchImpl: async (_url, { signal }) => {
      calls += 1;
      return await new Promise((_resolve, reject) => {
        signal.addEventListener("abort", () => reject(new DOMException("aborted", "AbortError")));
      });
    },
  }), /timed out/);
  assert.equal(calls, 1);
});

test("does not spend an API call on a forced single legal choice", async () => {
  const result = await chooseWithJev({
    apiKey: "test-only-key",
    state: { team: "red" },
    candidates: [candidates[1]],
    fetchImpl: async () => { throw new Error("must not call upstream"); },
  });
  assert.equal(result.choice, "wait");
  assert.equal(result.attempts, 0);
});
