%%{init: {"flowchart": {"htmlLabels": false}, "themeVariables": {"fontFamily": "Arial, sans-serif"}}}%%
flowchart TD
    splash("  Splash  ")
    game_mode("  Game Mode  ")
    map_select("  Map Select  ")
    gameplay("  Gameplay  ")
    splash -->|new_game| game_mode
    game_mode -->|select_regular| map_select
    game_mode -->|select_ctf| map_select
    game_mode -->|back| splash
    map_select -->|select_urban| gameplay
    map_select -->|select_hills| gameplay
    map_select -->|back| game_mode
