%%{init: {"flowchart": {"htmlLabels": false}, "themeVariables": {"fontFamily": "Arial, sans-serif"}}}%%
flowchart TD
    splash("  Splash  ")
    map_select("  Map Select  ")
    gameplay("  Gameplay  ")
    splash -->|new_game| map_select
    map_select -->|select_urban| gameplay
    map_select -->|select_hills| gameplay
    map_select -->|back| splash
