# Collects the map-seed goldens for the asset gallery (issue #133).
#
# Run in CMake script mode:
#   cmake -DGOLDENS_DIR=<repo>/tests/map_goldens -DOUT_DIR=<build dir> \
#         -P scripts/gen_gallery_map_seeds.cmake
#
# Copies every ${GOLDENS_DIR}/*.png into ${OUT_DIR}/map_goldens/ and writes
# ${OUT_DIR}/map_seeds.js listing the filenames, which web/gallery.html reads
# to build its "Map seeds" section. Globbing happens here, at build time, so
# a newly added golden appears in the gallery without touching the page.

if(NOT DEFINED GOLDENS_DIR OR NOT DEFINED OUT_DIR)
  message(FATAL_ERROR "Usage: cmake -DGOLDENS_DIR=... -DOUT_DIR=... -P gen_gallery_map_seeds.cmake")
endif()

file(GLOB pngs RELATIVE "${GOLDENS_DIR}" "${GOLDENS_DIR}/*.png")
list(SORT pngs)

file(MAKE_DIRECTORY "${OUT_DIR}/map_goldens")
set(entries "")
foreach(png IN LISTS pngs)
  file(COPY "${GOLDENS_DIR}/${png}" DESTINATION "${OUT_DIR}/map_goldens")
  string(APPEND entries "  \"${png}\",\n")
endforeach()

file(WRITE "${OUT_DIR}/map_seeds.js"
  "// Generated by scripts/gen_gallery_map_seeds.cmake; do not edit.\n"
  "window.MAP_SEED_GOLDENS = [\n${entries}];\n")
