#!/usr/bin/env python3
"""Generate the C++ screen enum + transition table from the flow YAML.

usage: gen_flow_cpp.py <flow.yaml> <out.h>
"""
import sys

import yaml


def main():
    src, out = sys.argv[1:3]
    with open(src) as f:
        flow = yaml.safe_load(f)
    states = [s["name"] for s in flow["states"]]
    events = []
    for t in flow["transitions"]:
        if t["event"] not in events:
            events.append(t["event"])
        for key in ("from", "to"):
            if t[key] not in states:
                sys.exit(f"{src}: unknown state '{t[key]}' in transition {t}")
    if flow["initial"] not in states:
        sys.exit(f"{src}: unknown initial state '{flow['initial']}'")

    lines = [
        "// Generated by scripts/gen_flow_cpp.py from src/flow/game_flow.yaml. Do not edit.",
        "#pragma once",
        "",
        "#include <array>",
        "#include <optional>",
        "",
        "namespace flow {",
        "",
        "enum class Screen { " + ", ".join(states) + " };",
        "enum class Event { " + ", ".join(events) + " };",
        "",
        f"constexpr Screen kInitialScreen = Screen::{flow['initial']};",
        "",
        "struct Transition {",
        "  Screen from;",
        "  Event event;",
        "  Screen to;",
        "};",
        "",
        f"constexpr std::array<Transition, {len(flow['transitions'])}> kTransitions = {{{{",
    ]
    for t in flow["transitions"]:
        lines.append(f"    {{Screen::{t['from']}, Event::{t['event']}, Screen::{t['to']}}},")
    lines += [
        "}};",
        "",
        "// Returns the screen reached by `event` from `from`, or nullopt if the flow",
        "// has no such transition.",
        "constexpr std::optional<Screen> Next(Screen from, Event event) {",
        "  for (const Transition& t : kTransitions) {",
        "    if (t.from == from && t.event == event) return t.to;",
        "  }",
        "  return std::nullopt;",
        "}",
        "",
        "}  // namespace flow",
        "",
    ]
    with open(out, "w") as f:
        f.write("\n".join(lines))


main()
