#!/usr/bin/env python3
"""Generate the app flow C++ header and Mermaid diagram from flow/app_flow.yaml.

usage: gen_flow.py <flow.yaml> --header <out.h> --mermaid <out.mmd>
Uses PyYAML when available, else a tiny parser for the restricted shape the
flow file uses (documented in the YAML header).
"""
import argparse
import re


def parse_minimal(text):
    doc = {"states": [], "transitions": []}
    section = None
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].rstrip()
        if not line.strip():
            continue
        if not line.startswith(" "):
            key, _, val = line.partition(":")
            val = val.strip()
            if val:
                doc[key.strip()] = val
                section = None
            else:
                section = key.strip()
                doc.setdefault(section, [])
            continue
        m = re.match(r"\s*-\s*\{(.*)\}\s*$", line)
        if not m or section is None:
            raise SystemExit(f"unsupported YAML line: {raw!r}")
        item = {}
        for pair in m.group(1).split(","):
            k, _, v = pair.partition(":")
            item[k.strip()] = v.strip()
        doc[section].append(item)
    return doc


def load(path):
    text = open(path, encoding="utf-8").read()
    try:
        import yaml
        return yaml.safe_load(text)
    except ImportError:
        return parse_minimal(text)


def camel(s):
    return "".join(p.capitalize() for p in s.split("_"))


def validate(doc):
    ids = [s["id"] for s in doc["states"]]
    if doc["initial"] not in ids:
        raise SystemExit("initial state not in states")
    events = set()
    for t in doc["transitions"]:
        if t["from"] not in ids or t["to"] not in ids:
            raise SystemExit(f"transition references unknown state: {t}")
        if (t["from"], t["event"]) in events:
            raise SystemExit(f"duplicate transition: {t}")
        events.add((t["from"], t["event"]))


def gen_header(doc):
    states = [s["id"] for s in doc["states"]]
    events = sorted({t["event"] for t in doc["transitions"]})
    o = ["// GENERATED by scripts/gen_flow.py from flow/app_flow.yaml. Do not edit.",
         "#pragma once", "", "namespace tbgwaf_flow {", "",
         "enum class State { " + ", ".join(camel(s) for s in states) + " };",
         "enum class Event { " + ", ".join(camel(e) for e in events) + " };", "",
         f"constexpr State kInitialState = State::{camel(doc['initial'])};", "",
         "struct Transition {", "  State from;", "  Event event;", "  State to;", "};", "",
         "constexpr Transition kTransitions[] = {"]
    for t in doc["transitions"]:
        o.append(f"    {{State::{camel(t['from'])}, Event::{camel(t['event'])}, "
                 f"State::{camel(t['to'])}}},")
    o += ["};", "",
          "// Next state for `event` fired in `from`; unchanged if no transition matches.",
          "constexpr State Next(State from, Event event) {",
          "  for (const Transition& t : kTransitions) {",
          "    if (t.from == from && t.event == event) return t.to;",
          "  }", "  return from;", "}", "", "}  // namespace tbgwaf_flow", ""]
    return "\n".join(o)


def gen_mermaid(doc):
    o = ["stateDiagram-v2"]
    for s in doc["states"]:
        o.append(f'    state "{s["label"]}" as {s["id"]}')
    o.append(f"    [*] --> {doc['initial']}")
    for t in doc["transitions"]:
        o.append(f"    {t['from']} --> {t['to']}: {t['event']}")
    return "\n".join(o) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("yaml")
    ap.add_argument("--header", required=True)
    ap.add_argument("--mermaid", required=True)
    a = ap.parse_args()
    doc = load(a.yaml)
    validate(doc)
    open(a.header, "w", encoding="utf-8").write(gen_header(doc))
    open(a.mermaid, "w", encoding="utf-8").write(gen_mermaid(doc))


if __name__ == "__main__":
    main()
